version: "2"
linters:
  enable:
    - goconst
    - gosec
    - lll
    - misspell
    - nakedret
    - paralleltest
    - revive
    - staticcheck
    - unconvert
  disable:
    - godot
  settings:
    revive:
      rules:
        - name: package-comments
          exclude:
            - '**/internal/**'
  exclusions:
    generated: lax
    paths:
      - vendor$
      - third_party$
      - testdata$
      - Godeps$
      - builtin$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - vendor$
      - third_party$
      - testdata$
      - Godeps$
      - builtin$
