run:
  timeout: 10m
issues:
  # Enable checking the by default skipped "examples" dirs
  exclude-dirs-use-default: false
  exclude-dirs:
    - vendor$
    - third_party$
    - testdata$
    - Godeps$
    - builtin$
linters:
  enable-all: false
  enable:
    - errcheck
    - goconst
    - gofmt
    - revive
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - unconvert
    - paralleltest
    - stylecheck
    - unused
  disable:
    - staticcheck # Disabled due to OOM errors in golangci-lint@v1.18.0
