run:
  timeout: 10m
issues:
  # Enable checking the by default skipped "examples" dirs
  exclude-dirs-use-default: false
  exclude-use-default: false
  exclude-dirs:
    - vendor$
    - third_party$
    - testdata$
    - Godeps$
    - builtin$
  exclude-rules:
    # Disable paralleltesting for these two functions that require global state.
    - linters: [paralleltest]
      text: "Function TestRegisterType missing the call to method parallel"
    - linters: [paralleltest]
      text: "Function TestProvider missing the call to method parallel"


linters:
  enable-all: false
  enable:
    - errcheck
    - goconst
    - gofmt
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - unconvert
    - paralleltest
    - staticcheck
    - stylecheck
    - unused
  disable:
    - godot
linters-settings:
  revive:
    rules:
      # Require that exported types and functions have comments.
      - name: package-comments
        # We do not require this for internal types.
        exclude: ["**/internal/**"]
