coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  # Examples implementation code should not count against coverage.
  - "examples/"
  - "infer/tests/mocks.gen.go"
