// Code generated by schema-test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package schematest

type Strct struct {
	Enum  *int     `pulumi:"enum"`
	Names []string `pulumi:"names"`
}

func init() {
}
