// Code generated by schema-test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package schematest

type Enum int

const (
	EnumA = Enum(0)
	EnumC = Enum(1)
	EnumT = Enum(2)
	EnumG = Enum(3)
)

func init() {
}
