package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"
)

func must[T any](t T, err error) T {
	if err != nil {
		panic(err)
	}
	return t
}

var applyFuncs = must(template.New("apply").Parse(
	`
func Apply{{.inputs}}[{{.inputTypes}}U any]({{.inputArgsWithTypes}}f func({{.inputTypesNoComma}}) U) Output[U] {
	return Apply{{.inputs}}Err({{.inputArgsNoTypes}}func({{.inputArgsRawTypes}}) (U, error) {
		return f({{.inputArsRaw}}), nil
	})
}

func Apply{{.inputs}}Err[{{.inputTypes}}U any]({{.inputArgsWithTypes}}f func({{.inputTypesNoComma}}) (U, error)) Output[U] {
	result := newOutput[U](nil, {{.orSecrets}}, deps{}{{.joinDeps}})
	go apply{{.inputs}Result({{.inputArgsNoTypes}}result, f)
	return result
}

func apply{{.inputs}}Result[{{.inputTypes}}U any]({{.inputArgs}}to Output[U], f func({{.inputTypesNoComma}}) (U, error)) {
	if {{.orCanResolve}} {
		return
	}
	{{.wait}}

	// Propagate the change
	to.join.L.Lock()
	defer to.join.L.Unlock()

	if err := errors.Join({{.errs}}); err == nil {
		tmp, err := f({{.values}})
		if err == nil {
			to.value = &tmp
		} else {
			to.err = err
		}
	} else {
		to.err = err
	}
	to.resolved = true
	to.join.Broadcast()
}
`))

func main() {
	b := new(bytes.Buffer)
	b.WriteString(`// Code generated by gen_apply/main; DO NOT EDIT.
package infer
`)
	for i := 0; i < 10; i++ {
		var inputs string
		if i > 0 {
			inputs = fmt.Sprintf("%d", i+1)
		}
		err := applyFuncs.Execute(b, map[string]string{
			"inputs":            inputs,                     // A number, like "3"
			"inputTypes":        formatN(1, i, "T%d, ", ""), // "T1, T2, T3, "
			"inputTypesNoComma": formatN(1, i, "T%d", ", "), // "T1, T2, T3"
			// "o1 Output[T1], o2 Output[T2], o3 Output[T3], "
			"inputArgsWithTypes": formatN(1, i, "o%[1]d Output[T%[1]d], ", ""),
			"inputArgsNoTypes":   formatN(1, i, "o%d, ", ""),           // "o1, o2, "
			"inputArgsRawTypes":  formatN(1, i, "v%[1]d T%[1]d", ", "), // "v1 T1, v2 T2"
			"inputArgsRaw":       formatN(1, i, "v%d", ", "),           // "v1, v2"
			"orSecrets":          formatN(1, i, "o%d.secret", " || "),  // "o1.secret || o2.secret"
			// "!o1.deps.canResolve() || !o1.deps.canResolve()"
			"orCanResolve": formatN(1, i, "!o%d.deps.canResolve()", " || "),
			"wait":         formatN(1, i, "o%d.wait()", "\n\t"),  // "o1.wait()\n\to2.wait()"
			"errs":         formatN(1, i, "o%d.err", ", "),       // "o1.err, o2.err"
			"values":       formatN(1, i, "*o%d.value", ", "),    // "*o1.value, *o2.value"
			"joinDeps":     formatN(1, i, ".join(o%d.deps)", ""), // ".join(o1.deps).join(o2.deps)"
		})
		if err != nil {
			panic(err)
		}
	}

	err := os.WriteFile(os.Args[1], b.Bytes(), 0600)
	if err != nil {
		panic(err)
	}
}

func formatN(from, to int, msg, join string) string {
	arr := make([]string, 0, to-from)
	for i := from; i < to; i++ {
		arr = append(arr, fmt.Sprintf(msg, i))
	}
	return strings.Join(arr, join)
}
