// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package randomlogin

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-go-provider/examples/random-login/sdk/go/randomlogin/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Generate a random password.
type MoreRandomPassword struct {
	pulumi.ResourceState

	Length   pulumi.IntOutput    `pulumi:"length"`
	Password pulumi.StringOutput `pulumi:"password"`
}

// NewMoreRandomPassword registers a new resource with the given unique name, arguments, and options.
func NewMoreRandomPassword(ctx *pulumi.Context,
	name string, args *MoreRandomPasswordArgs, opts ...pulumi.ResourceOption) (*MoreRandomPassword, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Length == nil {
		return nil, errors.New("invalid value for required argument 'Length'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource MoreRandomPassword
	err := ctx.RegisterRemoteComponentResource("random-login:index:MoreRandomPassword", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type moreRandomPasswordArgs struct {
	// The desired password length.
	Length int `pulumi:"length"`
}

// The set of arguments for constructing a MoreRandomPassword resource.
type MoreRandomPasswordArgs struct {
	// The desired password length.
	Length pulumi.IntInput
}

func (MoreRandomPasswordArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*moreRandomPasswordArgs)(nil)).Elem()
}

type MoreRandomPasswordInput interface {
	pulumi.Input

	ToMoreRandomPasswordOutput() MoreRandomPasswordOutput
	ToMoreRandomPasswordOutputWithContext(ctx context.Context) MoreRandomPasswordOutput
}

func (*MoreRandomPassword) ElementType() reflect.Type {
	return reflect.TypeOf((**MoreRandomPassword)(nil)).Elem()
}

func (i *MoreRandomPassword) ToMoreRandomPasswordOutput() MoreRandomPasswordOutput {
	return i.ToMoreRandomPasswordOutputWithContext(context.Background())
}

func (i *MoreRandomPassword) ToMoreRandomPasswordOutputWithContext(ctx context.Context) MoreRandomPasswordOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MoreRandomPasswordOutput)
}

// MoreRandomPasswordArrayInput is an input type that accepts MoreRandomPasswordArray and MoreRandomPasswordArrayOutput values.
// You can construct a concrete instance of `MoreRandomPasswordArrayInput` via:
//
//	MoreRandomPasswordArray{ MoreRandomPasswordArgs{...} }
type MoreRandomPasswordArrayInput interface {
	pulumi.Input

	ToMoreRandomPasswordArrayOutput() MoreRandomPasswordArrayOutput
	ToMoreRandomPasswordArrayOutputWithContext(context.Context) MoreRandomPasswordArrayOutput
}

type MoreRandomPasswordArray []MoreRandomPasswordInput

func (MoreRandomPasswordArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MoreRandomPassword)(nil)).Elem()
}

func (i MoreRandomPasswordArray) ToMoreRandomPasswordArrayOutput() MoreRandomPasswordArrayOutput {
	return i.ToMoreRandomPasswordArrayOutputWithContext(context.Background())
}

func (i MoreRandomPasswordArray) ToMoreRandomPasswordArrayOutputWithContext(ctx context.Context) MoreRandomPasswordArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MoreRandomPasswordArrayOutput)
}

// MoreRandomPasswordMapInput is an input type that accepts MoreRandomPasswordMap and MoreRandomPasswordMapOutput values.
// You can construct a concrete instance of `MoreRandomPasswordMapInput` via:
//
//	MoreRandomPasswordMap{ "key": MoreRandomPasswordArgs{...} }
type MoreRandomPasswordMapInput interface {
	pulumi.Input

	ToMoreRandomPasswordMapOutput() MoreRandomPasswordMapOutput
	ToMoreRandomPasswordMapOutputWithContext(context.Context) MoreRandomPasswordMapOutput
}

type MoreRandomPasswordMap map[string]MoreRandomPasswordInput

func (MoreRandomPasswordMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MoreRandomPassword)(nil)).Elem()
}

func (i MoreRandomPasswordMap) ToMoreRandomPasswordMapOutput() MoreRandomPasswordMapOutput {
	return i.ToMoreRandomPasswordMapOutputWithContext(context.Background())
}

func (i MoreRandomPasswordMap) ToMoreRandomPasswordMapOutputWithContext(ctx context.Context) MoreRandomPasswordMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MoreRandomPasswordMapOutput)
}

type MoreRandomPasswordOutput struct{ *pulumi.OutputState }

func (MoreRandomPasswordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MoreRandomPassword)(nil)).Elem()
}

func (o MoreRandomPasswordOutput) ToMoreRandomPasswordOutput() MoreRandomPasswordOutput {
	return o
}

func (o MoreRandomPasswordOutput) ToMoreRandomPasswordOutputWithContext(ctx context.Context) MoreRandomPasswordOutput {
	return o
}

func (o MoreRandomPasswordOutput) Length() pulumi.IntOutput {
	return o.ApplyT(func(v *MoreRandomPassword) pulumi.IntOutput { return v.Length }).(pulumi.IntOutput)
}

func (o MoreRandomPasswordOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v *MoreRandomPassword) pulumi.StringOutput { return v.Password }).(pulumi.StringOutput)
}

type MoreRandomPasswordArrayOutput struct{ *pulumi.OutputState }

func (MoreRandomPasswordArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MoreRandomPassword)(nil)).Elem()
}

func (o MoreRandomPasswordArrayOutput) ToMoreRandomPasswordArrayOutput() MoreRandomPasswordArrayOutput {
	return o
}

func (o MoreRandomPasswordArrayOutput) ToMoreRandomPasswordArrayOutputWithContext(ctx context.Context) MoreRandomPasswordArrayOutput {
	return o
}

func (o MoreRandomPasswordArrayOutput) Index(i pulumi.IntInput) MoreRandomPasswordOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *MoreRandomPassword {
		return vs[0].([]*MoreRandomPassword)[vs[1].(int)]
	}).(MoreRandomPasswordOutput)
}

type MoreRandomPasswordMapOutput struct{ *pulumi.OutputState }

func (MoreRandomPasswordMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MoreRandomPassword)(nil)).Elem()
}

func (o MoreRandomPasswordMapOutput) ToMoreRandomPasswordMapOutput() MoreRandomPasswordMapOutput {
	return o
}

func (o MoreRandomPasswordMapOutput) ToMoreRandomPasswordMapOutputWithContext(ctx context.Context) MoreRandomPasswordMapOutput {
	return o
}

func (o MoreRandomPasswordMapOutput) MapIndex(k pulumi.StringInput) MoreRandomPasswordOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *MoreRandomPassword {
		return vs[0].(map[string]*MoreRandomPassword)[vs[1].(string)]
	}).(MoreRandomPasswordOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MoreRandomPasswordInput)(nil)).Elem(), &MoreRandomPassword{})
	pulumi.RegisterInputType(reflect.TypeOf((*MoreRandomPasswordArrayInput)(nil)).Elem(), MoreRandomPasswordArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MoreRandomPasswordMapInput)(nil)).Elem(), MoreRandomPasswordMap{})
	pulumi.RegisterOutputType(MoreRandomPasswordOutput{})
	pulumi.RegisterOutputType(MoreRandomPasswordArrayOutput{})
	pulumi.RegisterOutputType(MoreRandomPasswordMapOutput{})
}
