name: Run Acceptance Tests on main

on:
  push:
    branches:
    - main

jobs:
  lint:
    uses: ./.github/workflows/stage-lint.yml
  test:
    uses: ./.github/workflows/stage-test.yml
    with:
      live-test: true
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      CODECOV_TOKEN:       ${{ secrets.CODECOV_TOKEN }}
