name: Release

on:
  push:
    tags:
      - v*.*.*
      - "!v*.*.*-**"

jobs:
  ensure-version:
    runs-on: ubuntu-latest
    name: Ensure .version file is up to date
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ensure version
        run: |
          if [ ! -f ".version" ]; then
            echo "No .version file found"
            exit 1
          fi
          if [ "v$(cat .version)" != ${{ github.ref_name }} ]; then
            echo 'The release has failed.'
            echo
            echo The version in ".version" file "(v$(cat .version))" does 
            echo not match tag pushed (${{ github.ref_name }}). The releaser
            echo needs to manually delete the release and any associated git
            echo tag, update the .version file and try again.
            exit 1
          fi
  lint:
    uses: ./.github/workflows/stage-lint.yml
  test:
    uses: ./.github/workflows/stage-test.yml
    with:
      live-test: true
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  publish:
    needs: [ensure-version, lint, test]
    runs-on: ubuntu-latest
    steps:
    - name: Create GH Release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
      with:
            generate_release_notes: true
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
