permissions: write-all # Equivalent to default permissions plus id-token: write
name: Test

on:
  workflow_call:
    inputs:
      live-test:
        description: |
          Whether to run tests against a live environment. When false, tests that require secrets
          should be skipped.
        default: false
        required: false
        type: boolean
      python-version:
        description: "Version of the Python toolchain for the build"
        default: "3.9.x"
        required: false
        type: string
      node-version:
        description: "Version of the Node toolchain for the build"
        default: "14.x"
        required: false
        type: string
      dotnet-version:
        description: "Version of the .NET toolchain for the build"
        default: "3.1.x"
        required: false
        type: string
      commit-ref:
        description: Commit ref to check out and run tests against.
        default: ""
        required: false
        type: string
    secrets:
      PULUMI_ACCESS_TOKEN: {required: false}
      CODECOV_TOKEN: {required: false}

env:
  PULUMI_LIVE_TEST: ${{ inputs.live-test }}
  PULUMI_API: https://api.pulumi-staging.io
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PULUMI_TEST_PARALLEL: false
  NODE_OPTIONS: --max-old-space-size=3072
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: PULUMI_ACCESS_TOKEN,CODECOV_TOKEN

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@8afe12bb7bb3df0a599e5309ee429ff1079ba85f # v3
      - name: Checkout Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          ref: ${{ inputs.commit-ref }}
      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@b374ceb6168550de27c6eba92e01c1a774040e11 # v2
      - name: Test
        run: make test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        env:
          CODECOV_TOKEN: ${{ steps.esc-secrets.outputs.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - stable
          - oldstable
